[profile.release]
strip = true
lto = true
panick = "abort"

[package]
name = "passman"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
chacha20 = "0.9"
blake2 = "0.9"
rpassword = "6"
